In [1]:
import numpy as np

def apply_u(psi,u,idx):
    l = len(u.shape)//2; L = len(psi.shape)
    psi = np.tensordot(psi,u,axes=(idx,range(l)))
    psi = psi.transpose([*range(idx[0])] + 
                        [*range(L-l,L)] + 
                        [*range(idx[0],L-l)])
    return psi

def print_amplitudes(psi):
  L = len(psi.shape)
  for i in range(2**L):
    X =  np.array([0]*(L - len(list(bin(i)[2:]))) + list(bin(i)[2:]),dtype=int)
    print(X,":",psi.reshape(2**L)[i])

In [2]:
CNOT = np.array([[1,0,0,0],
                 [0,1,0,0],
                 [0,0,0,1],
                 [0,0,1,0]]).reshape([2,2,2,2])

H = 1/np.sqrt(2)*np.array([[1, 1],
                           [1,-1]])
L = 3
psi = np.zeros(2**L);psi[0]=1.;
psi = psi.reshape(L*[2])

psi = apply_u(psi,H,[0])
psi = apply_u(psi,H,[1])
psi = apply_u(psi,CNOT,[1,2])

print_amplitudes(psi)

[0 0 0] : 0.4999999999999999
[0 0 1] : 0.0
[0 1 0] : 0.0
[0 1 1] : 0.4999999999999999
[1 0 0] : 0.4999999999999999
[1 0 1] : 0.0
[1 1 0] : 0.0
[1 1 1] : 0.4999999999999999
