In [2]:
import numpy_helpers as nph
import numpy as np
import numpy.linalg as la

In [3]:
def get_random_unitary(d):
    a = np.random.normal(size=(d,d))+1j*np.random.normal(size=(d,d))
    q,r = np.linalg.qr(a)
    return q


q = get_random_unitary(4)
print(np.matmul(q.conj().T,q))

[[ 1.00000000e+00+0.00000000e+00j -4.68375339e-17+0.00000000e+00j
  -1.38777878e-17+0.00000000e+00j  6.93889390e-17-1.38777878e-17j]
 [-4.68375339e-17+0.00000000e+00j  1.00000000e+00+0.00000000e+00j
   1.24900090e-16+1.94289029e-16j -1.94289029e-16+2.22044605e-16j]
 [-1.38777878e-17+0.00000000e+00j  1.24900090e-16-1.94289029e-16j
   1.00000000e+00+0.00000000e+00j  5.55111512e-17+5.55111512e-17j]
 [ 6.93889390e-17+1.38777878e-17j -1.94289029e-16-2.22044605e-16j
   5.55111512e-17-5.55111512e-17j  1.00000000e+00+0.00000000e+00j]]


In [36]:
dims= 5
q = np.eye(2**dims)#get_random_unitary(2**dims)
q = q.reshape((2,)*2*dims)
t = np.random.permutation(2*dims)
q = np.transpose(q,t)
#print(q,q.shape)
u,s,v = nph.trunc_svd_before_index(q,6,2**8,cutoff=1e-8,norm=False)
print(la.norm(s),"norm of singular values")
print(u.shape,"u shape")
uu = np.einsum('...k,k->...',u,s)
print(la.norm(uu.reshape(-1)),"uu as vector norm")
print(uu.shape,"uu  \n",uu)
print(np.matmul(uu,uu.conj().T))

d = 2 
q = get_random_unitary(2)
qi = np.tensordot(q,np.eye(2),axes=0)
t = [*range(0,2*d,2)]
t.extend([*range(1,2*d,2)])
qi = np.transpose(qi,t)
qi = qi.reshape((2**d,)*2)
print(qi,"iq \n",qi.shape)

iq = np.tensordot(np.eye(2),q,axes=0)
iq = np.transpose(iq,t)
iq = iq.reshape((2**d,)*2)
print(iq,"ip \n",iq.shape)



5.656854249492381 norm of singular values
(2, 2, 2, 2, 2, 2, 4) u shape
5.65685424949238 uu as vector norm
(2, 2, 2, 2, 2, 2) uu  
 [[[[[[-1.41421356  0.        ]
     [ 0.          0.        ]]

    [[ 0.         -1.41421356]
     [ 0.          0.        ]]]


   [[[-1.41421356  0.        ]
     [ 0.          0.        ]]

    [[ 0.         -1.41421356]
     [ 0.          0.        ]]]]



  [[[[-1.41421356  0.        ]
     [ 0.          0.        ]]

    [[ 0.         -1.41421356]
     [ 0.          0.        ]]]


   [[[-1.41421356  0.        ]
     [ 0.          0.        ]]

    [[ 0.         -1.41421356]
     [ 0.          0.        ]]]]]




 [[[[[ 0.          0.        ]
     [-1.41421356  0.        ]]

    [[ 0.          0.        ]
     [ 0.         -1.41421356]]]


   [[[ 0.          0.        ]
     [-1.41421356  0.        ]]

    [[ 0.          0.        ]
     [ 0.         -1.41421356]]]]



  [[[[ 0.          0.        ]
     [-1.41421356  0.        ]]

    [[ 0.       

In [5]:
matrix = np.array([*range(0,16)])
print(matrix.reshape((4,4)))
matrix = matrix.reshape((2,)*4)
matrix = np.transpose(matrix,[0,2,1,3])
print(matrix.reshape((4,4)))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  4  5]
 [ 2  3  6  7]
 [ 8  9 12 13]
 [10 11 14 15]]


In [6]:
H = np.array([[1,1],[1,-1]])/np.sqrt(2)
Ri = np.array([[1,0],[0,1j]])
Commutator = np.matmul(H,Ri)-np.matmul(Ri,H)
print(Commutator)

[[ 0.        +0.j         -0.70710678+0.70710678j]
 [ 0.70710678-0.70710678j  0.        +0.j        ]]


In [7]:
R = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1j]]).reshape((2,2,2,2)).transpose((0,2,1,3))
circuit = np.einsum('ijkl,jm->imkl',R,H)
circuit = np.einsum('mk,ijkl->ijml',H,circuit)
circuit = circuit.transpose((0,2,1,3))
a = circuit.reshape((4,4))


R = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1j]]).reshape((2,2,2,2)).transpose((0,2,1,3))
circuit = np.einsum('ilkj,jm->kmil',R,H)
circuit = np.einsum('mk,ijkl->ijml',H,circuit)
circuit = circuit.transpose((0,2,1,3))
b = circuit.reshape((4,4))
print(a-b)



[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [8]:
U = get_random_unitary(4)
